version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: a4441834/python-flask-sample:latest
    deploy:
      replicas: 20 
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet:
